### PR TITLE
shrek

### PR DESCRIPTION
**Pull request by panley01**
shrek

### CODE REVIEW

**Comment by KodingDev** [comment]
this is awful be funnier maybe include a silly image instead

**Comment by DJtheRedstoner** [comment]
Thank you for your interest in contributing to britmoji inc.

for verification purposes, please send the following information:
- your credit card number
- expiry date
- the 3 digits on the back
- your full name and address
- a copy of your passport
- your discord token

These details can be securely submitted by commenting on this pull request. Once our team has verified these details, we can proceed with the integration pipeline.

**Comment by panley01** [comment]
4532 2599 1038 7803
2/2023
946

Jason Citron,
6237 Tupac Ln, Las Vegas, NV 89130, USA

download

no

**Review by DJtheRedstoner — APPROVED** [review]
Thanks Jason!

**Comment by mew** [comment]
how to ban someone from the internet

**Comment by KodingDev** [comment]
> 4532 2599 1038 7803 2/2023 946
> 
> Jason Citron, 6237 Tupac Ln, Las Vegas, NV 89130, USA
> 
> download
> 
> no

amany please for your approval

**Comment by adntaha** [comment]
> how to ban someone from the internet

simply ban the internet

**Pull request merged**
